[package]
name = "halfbit"
version = "0.0.0"
authors = ["Costin Ionescu <costin.ionescu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = ">= 0.1"

[lib]
name = "halfbit"

[[example]]
name = "hb"

